[package]
name = "pokedex-gen"
version = "0.2.0"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"

[dependencies]
tokio = { version = "1", features = ["fs", "macros", "time", "rt-multi-thread"] }
pokerust = { path = "./pokerust" }
reqwest = { version = "0.11.0" }
serde = { version = "1.0", features = ["derive"] }
image = { version = "0.23.12", default-features = false, features = ["png"] }
log = "0.4.0"
simple_logger = { version = "1", default-features = false }
ron = "0.6"
firecore-pokedex = { git = "https://github.com/DoNotDoughnut/pokemon-game", package = "firecore-pokedex" }
anyhow = "1"

[workspace]
members = ["pokerust"]