[package]
name = "pokedex-gen"
version = "0.1.0"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"

[dependencies]
tokio = { version = "1", features = ["fs", "macros", "time", "rt-multi-thread"] }
pokerust = { path = "./pokerust" }
reqwest = { version = "0.11.0", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
image = { version = "0.23.12", default-features = false, features = ["png"] }
# toml = "0.5"
ron = "0.6"
firecore-pokedex = { git = "https://github.com/DoNotDoughnut/pokemon-game", package = "firecore-pokedex" }
# lazy_static = "1.4.0"

[workspace]
members = ["pokerust"]